deploy-to-server:
    needs: build-and-push
    runs-on: self-hosted
    steps:
      - name: Update Kubernetes
        run: |
          # Perintah ini dijalankan LANGSUNG di dalam server Ubuntu Anda
          microk8s kubectl set image deployment/my-webapp my-webapp=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          microk8s kubectl rollout restart deployment/my-webapp